version: "3.8"
services:
  docker-apache:
    image: phpcrypton:latest
    container_name: docker-apache
    ports:
      - "80:80"
    links:
      - mysql-db

  mysql-db:
    image: mysql:latest
    container_name: docker-mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: badcrud
    ports:
      - "3306:3306"
    volumes:
      - ./db/badcrud.sql:/docker-entrypoint-initdb.d/badcrud.sql:ro