name: PHPCrypton Functional Testing

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Functional Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Create isolated network
        run: docker network create --driver bridge isolated      

      - name: Build PHPCrypton
        run: docker build -t phpcrypton:latest .

      - name: Run PHPCrypton using docker-compose
        run: docker-compose up -d

      - name: Check container
        run: docker ps

      - name: Copy source code to container
        run: docker cp ./web2 docker-apache:/var/www/html

      - name: Check inside container
        run: docker exec docker-apache ls /var/www/html/

      - name: Get Container URL
        run: |
          URL=http://$(ip -f inet -o addr show docker0 | awk '{print $4}' | cut -d '/' -f 1)
          echo "URL=$URL" >> $GITHUB_ENV

      - name: Check Container URL
        run: curl -L ${{ env.URL }}

      # - name: Check Container URL
      #   run: curl http://localhost

      # - name: ZAP Scan
      #   uses: hermanka/action-full-scan@master
      #   with:
      #     target: http://${{ env.URL }}
      #     network_name: isolated
          
      - name: stop docker
        run: docker stop docker-apache

